### ISSUE TITLE
More compact config for bridges

### ISSUE THREAD

**Issue by ekshaks** [ekshaks/ragpipe#11]
Currently, there is high repetition of field names.

```bridges:
  b_dense:
      repnodes: query.text#dense, .documents[].description#dense
      limit: 10
  b_dense2:
      repnodes: query.text#dense2, .documents[].description#dense2
      limit: 100
  b_densebin:
      repnodes: query.text#densebin, .documents[].description#densebin
      limit: 10
  b_sparse:
     repnodes: query.text#sparse, .documents[].description#sparse
     limit: 10
```

Suggest a more Compact form
```
bridges:
  b:
    fields: query.text, .documents[].description
    reps: dense, dense2, densebin, sparse
```

or with per-rep options

```
  b:
    fields: query.text, .documents[].description
    reps:
      - dense: {limit: 10}
      - dense2 #default limit 10
      - densebin
      - sparse
```
